version: '3'

services:
  api:
    build:
      context: .
      target: builder
    container_name: superdrinks-server
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./app:/app